### ISSUE TITLE
Source env scripts for VM automatically

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-client#44]
## Overview

Add an NPM script to source Minikube automatically prior to running `npm start`. In the near future it would be nice to have this as a configurable option that defaults to Minikube (Kubernetes) when running just `npm start`.
## Reference
- [Make sourcing env scripts configurable](45)

**Comment by kahboom** [comment]
These are the new commands for starting the UI up, specific to Kubernetes or OpenShift:

For Minikube:
`npm start:minikube`

For Minishift:
`npm start:minishift`

And `npm start` will not source any of the env scripts, so you'd have to do them manually until we make them configurable, as stated above.

**Comment by kahboom** [comment]
Reopened, as I haven't written tests for this yet.

**Comment by gashcrumb** [comment]
This probably needs to get moved to ipaas-api, but I wonder, 1) is it possible and 2) is it still applicable

**Comment by kahboom** [comment]
We should move it anyway and decide later on, I think. Just don't want to forget about it in the event that it's still relevant.

**Comment by gashcrumb** [comment]
Yep, let me do that now...

**Comment by gashcrumb** [comment]
Moved to https://github.com/redhat-ipaas/ipaas-api/issues/14
