### ISSUE TITLE
Make sourcing env scripts configurable

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-client#45]
## Overview

Once #44 is completed, you'll be able to run `npm start:minikube` without having to source for Minikube (Kubernetes), or `npm start:minishift` for Minishift (OpenShift), but it would be nice to have it as a completely configurable option, possibly with Minikube as the default value.
## Reference
- [Source VM scripts automatically](44)

**Comment by gashcrumb** [comment]
Moved to https://github.com/redhat-ipaas/ipaas-api/issues/15
