### ISSUE TITLE
iPaaS Public Demo

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-client#48]
## Overview

Provide a demo that is publicly available (or maybe only when connected to the RH VPN) for others to view the progress of the front end application. Research whether or not this would be possible without the requirement of the backend or the Fabric8 platform running. This could be a live running instance of iPaaS or a build directory that can be loaded with Rawgit (would require complete independence from the backend).

**Comment by gashcrumb** [comment]
Have CI building the code in dev mode so far, building in prod mode yields a bunch of errors after minification, looking into that currently.

**Comment by gashcrumb** [comment]
CI link -> https://circleci.com/gh/hawtio/hawtio-ipaas

**Comment by kahboom** [comment]
Yayyyyyy!!! :D

**Comment by kahboom** [comment]
Assigning myself to this as well, since I'll be using GitHub pages to use the proper branch with built files, or the docs dir.
