### ISSUE TITLE
Connections: Edit a Connection's Labels

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-client#54]
## Overview
Write the logic and UI for the Edit Connection Labels page.

## Reference
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-40)
- [Connections: Create Connection](41)
- [Connections: Edit a Connection](53)

### InVision Designs:
- [Create a Connection Step One](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/188000725)

**Comment by kahboom** [comment]
This has been completed as an Angular module. It consists of a template that renders data loaded from an external service (the iPaaS API) through its primary component. Aesthetic improvements and other features require a separate GitHub issue.
