### ISSUE TITLE
Move some backend bits over to ipaas-api

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-client#63]
Since ipaas-client is only going to use ipaas-api we don't need bits for talking to forge/kubernetes/git kicking around in ipaas-client.  We should move these to https://github.com/redhat-ipaas/ipaas-api.

To move:

1.  [These scripts](https://github.com/redhat-ipaas/ipaas-client/tree/master/scripts)
1.  [This block of code](https://github.com/redhat-ipaas/ipaas-client/blob/master/config/webpack.common.js#L34-L116)
1.  [The forge service](https://github.com/redhat-ipaas/ipaas-client/blob/master/src/app/common/service/forge.ts)
1.  [The kubernetes service](https://github.com/redhat-ipaas/ipaas-client/blob/master/src/app/common/service/kubernetes.ts)
1.  [The git service](https://github.com/redhat-ipaas/ipaas-client/blob/master/src/app/common/service/git.ts)
1.  [The forge, kubernetes helper functions here](https://github.com/redhat-ipaas/ipaas-client/tree/master/src/app/common/helpers) along with the related tests.
1.  [This whole module](https://github.com/redhat-ipaas/ipaas-client/tree/master/src/app/%2Btesting) might be worth converting some of it into docs for the forge/kubernetes code.

@kahboom anything else you can think of?

**Comment by kahboom** [comment]
That sounds good @gashcrumb ! I can start helping move things over.

**Comment by gashcrumb** [comment]
@kahboom am happy to do it, just want to be sure I haven't missed anything.

**Comment by gashcrumb** [comment]
To start off with I'm extracting out all the bits I've mentioned and am going to put them in a 'sandbox' directory in ipaas-api, I'll add a readme and add a mention of it in the overview for historical purposes

**Comment by gashcrumb** [comment]
I wonder if we even need to keep the little oauth code I added, probably not, wdyt @kahboom?

**Comment by kahboom** [comment]
@gashcrumb Sounds good! The API is secured (erhmm "secured") for the most part.. we'll discuss it once I can start working on it again.

**Comment by gashcrumb** [comment]
I think this is all in place.
