### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-client#86]
Implement lazy loading that also working with AOT.

**Comment by jimmidyson** [comment]
We should also think about using the router to preload modules ala https://vsavkin.com/angular-router-preloading-modules-ba3c75e424cb

**Comment by kahboom** [comment]
@jimmidyson - Wasn't this done already? Can this be closed? I'm using the Projects kanban board to track what's missing and what isn't.

**Comment by jimmidyson** [comment]
Done.
