### ISSUE TITLE
AOT

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-client#87]
Implement AOT that also works with lazy loading.

**Comment by jimmidyson** [comment]
Wondering if switch to angular cli would make stuff like this easier as it comes ootb without us having to fight with webpack (which is a black art to me atm). I have a basic structure working with angular cli which simplifies a lot of stuff I think. What do you think?

**Comment by kahboom** [comment]
@jimmidyson - Same question for this issue as for the lazy loading #86 issue.

**Comment by jimmidyson** [comment]
Yep this is done now with move to angular cli.
