### ISSUE TITLE
Consider immutable state store

### ISSUE THREAD

**Issue by jimmidyson** [redhat-ipaas/ipaas-client#99]
Using something like [@ngrx/store](https://github.com/ngrx/store) perhaps. Allows us to use OnPush change detection but requires us to switch to immutable objects, probably using immutablejs. Although the architecture might feel more complicated at first it did give us more consistency across components regardless of nesting & hopefully give an even more reactive ux.

**Comment by jimmidyson** [comment]
This also includes a move to split up the UI into smart (container) components & presentational components. We can do this piece by piece so we can figure out the best structure as we go. A good blog post on this is http://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why/.

**Comment by jimmidyson** [comment]
I've pushed a start of this kind of refactor to my fork at https://github.com/jimmidyson/ipaas-client/tree/component-store-refactor. This doesn't yet include a separate store, but migrates to angular-cli & has what feels to me like a cleaner separation of smart & presentation components, albeit only for integration list page atm to show the approach.

@kahboom or @gashcrumb - I'd appreciate feedback. At the least, this has been an exercise for me to learn angular2 so if you disagree with the approach then no worries at all!

**Comment by gashcrumb** [comment]
I say merge it, let's take the hit now where we have less to re-work to fit the new paradigm :-)

**Comment by jimmidyson** [comment]
OK kewl - will tidy up a little bit what I have. It's going to be a branch switcheroo rather than a merge, otherwise it will take ages to do a rebase (well i could just delete all existing files i guess).

**Comment by jimmidyson** [comment]
Um well slightly scarily I've just switcherood master to the new style. Old master is on master-original branch, which in time we can delete but necessary for now to ensure we haven't lost anything.

Let me know if you have any questions when you get started with the new master.

**Comment by kahboom** [comment]
Thanks @jimmidyson !
